"""Generates BacktestEngine C++ strategy classes from the panes built in the
main GUI.

The set of strategy versions is the cross-product of each pane's template groups
(delimiter-separated), exactly as in StrategyGeneratorTS. Unlike the TS tool —
which emitted one EasyLanguage file with every version gated by a `StrategyVer`
input — each version here becomes its own C++ class in one generated header, and
is registered under its own name. Per-version classes mean input prefixes only
have to be unique within a version (E1_, X1_, S1_), with no V-part.

Registration is manifest-driven: `manifest.json` records which registry entries
belong to which generated header, so several strategy batches can coexist in the
engine tree and `headers.inc` / `registry.inc` can be rewritten wholesale on
every run.
"""

import os
import re
import json
import itertools
from dataclasses import dataclass, field

import ruleIO
from parameterGUI import rowIterations
from rule import CPP_KEYWORDS

# Characters Windows forbids in file names (the strategy name becomes a file name).
ILLEGAL_NAME_CHARS = re.compile(r'[\\/:*?"<>|]')

MANIFEST_NAME = "manifest.json"
HEADERS_INC = "headers.inc"
REGISTRY_INC = "registry.inc"

# How registry.cpp includes the generated headers (always forward slashes).
INCLUDE_DIR = "bt/strategies/generated"

_AUTOGEN = "Auto-generated by StrategyGeneratorBE. Do not edit by hand."

# MSVC warnings that generated code provokes by construction: unused ctx/aliases
# when a version's rules never touch them (4100/4101/4189), and the double->int
# narrowing of an input used as a series subscript (4244), which is intended.
# 4456 covers a hook that shadows an alias.
_MSVC_WARNINGS = "4100 4101 4189 4244 4456"

_ALIASES = ("open", "high", "low", "close", "volume")


class GenerationError(Exception):
    """Anything that would emit a header which does not compile, or an input grid
    the engine would reject at load. The GUI shows the message verbatim."""


# --- names ------------------------------------------------------------------

def sanitizeIdentifier(name):
    """Fold a strategy name into a C++ identifier fragment: "Momentum Clone 2"
    -> "Momentum_Clone_2"."""
    ident = re.sub(r"[^0-9A-Za-z]+", "_", name).strip("_")
    if not ident or ident[0].isdigit():
        ident = "S_" + ident
    if ident in CPP_KEYWORDS:
        raise GenerationError(f"Strategy name '{name}' is a C++ keyword.")
    return ident


def headerFileName(strategyName):
    return "gen_" + sanitizeIdentifier(strategyName).lower() + ".h"


def className(strategyName, version):
    return f"Gen_{sanitizeIdentifier(strategyName)}_V{version}"


def registryName(strategyName, version):
    """The engine's map key and the spec's "strategy" value. The raw name is
    used as-is; spaces are fine in a std::map<std::string> key."""
    return f"{strategyName} V{version}"


def specStem(strategyName, version):
    """Run-directory stem, shared with specWriter: "momentum_clone_v1"."""
    return f"{sanitizeIdentifier(strategyName).lower()}_v{version}"


# --- text helpers -----------------------------------------------------------

def _renameVars(text, names, prefix):
    """Prefix every whole-word occurrence of each declared name. C++ is
    case-sensitive, so unlike the TS original this match is too. Longest names
    go first so one name that contains another is not half-rewritten."""
    if not text:
        return text
    for name in sorted(names, key=len, reverse=True):
        pat = re.compile(r"(?<![A-Za-z0-9_])" + re.escape(name) + r"(?![A-Za-z0-9_])")
        text = pat.sub(prefix + name, text)
    return text


def _indent(text, level):
    pad = "    " * level
    return "\n".join(pad + ln if ln.strip() else ln for ln in text.splitlines())


# --- occurrences ------------------------------------------------------------

class _Occ:
    """One placed rule (a RuleItem) within one strategy version, paired with its
    loaded Rule definition and a unique variable prefix."""

    def __init__(self, item, rule, prefix, role):
        self.item = item
        self.rule = rule
        self.prefix = prefix
        self.role = role  # "entry" | "exit" | "switch"

    def _varNames(self):
        # Inputs and locals share one prefix namespace within an occurrence.
        names = dict(self.rule.inputVariables)
        names.update(self.rule.localVariables)
        return names

    def _renamed(self, text):
        return _renameVars(text, self._varNames(), self.prefix)

    def conditions(self):
        """Effective (long, short) C++ expressions with Flip/Negate and variable
        renaming applied. An empty string means "no constraint" and is skipped
        by the caller (AND-true / OR-false identity)."""
        long_ = self.rule.longCondition or ""
        short_ = self.rule.shortCondition or ""
        if getattr(self.item, "flipped", False):
            long_, short_ = short_, long_
        long_ = self._renamed(long_).strip()
        short_ = self._renamed(short_).strip()
        if getattr(self.item, "negated", False):
            if long_:
                long_ = "!( " + long_ + " )"
            if short_:
                short_ = "!( " + short_ + " )"
        return long_, short_

    def hook(self, attr):
        """A hook's raw C++, renamed. Unlike the TS version nothing is done about
        semicolons — hook text is C++ statements, written as such by the author."""
        text = getattr(self.rule, attr, "") or ""
        if not text.strip():
            return ""
        return self._renamed(text).rstrip()

    def inputDecls(self):
        """(prefixedName, start, stop, step) per input variable, taken from this
        placement's params. A blank Stop or Step pins the input to a single value
        as DeclareInput(name, v, v, 0) — grid.cpp returns 1 iteration for
        stop == start before it ever looks at the step."""
        result = []
        params = getattr(self.item, "params", {}) or {}
        for name, default in self.rule.inputVariables.items():
            p = params.get(name, {}) or {}
            start = (p.get("start") or "").strip()
            stop = (p.get("stop") or "").strip()
            step = (p.get("step") or "").strip()
            if not start:
                start = str(default).strip() or "0"
            if not stop or not step or stop == start:
                stop, step = start, "0"
            if rowIterations(start, stop, step) is None:
                raise GenerationError(
                    f"Rule '{self.rule.name}', variable '{name}': "
                    f"{start} to {stop} step {step} is not a valid optimizer range. "
                    "Stop must be at or above Start, and the span must divide "
                    "evenly by the Step."
                )
            result.append((self.prefix + name, start, stop, step))
        return result

    def localDecls(self):
        """(prefixedName, type, init) per local variable; each becomes a class
        member, so it persists across bars like an EasyLanguage `variables:`."""
        return [
            (self.prefix + name, spec.get("type", ""), spec.get("init", ""))
            for name, spec in self.rule.localVariables.items()
        ]


# --- version enumeration (ported from StrategyGeneratorTS) ------------------

def _templateGroups(items):
    """Split a pane's item list into delimiter-separated groups. N delimiters
    yield N+1 groups; empty groups are kept (a valid "do nothing" template)."""
    groups = [[]]
    for item in items:
        if isinstance(item, str):  # a DELIMITER line
            groups.append([])
        else:
            groups[-1].append(item)
    return groups


def _enumerateVersions(panes):
    """Cross-product of every pane's template groups. Each version is a tuple
    (entries, exits, switches) of RuleItem lists."""
    if not panes:
        return []
    paneGroups = [_templateGroups(p.items) for p in panes]
    paneTypes = [p.ruleType for p in panes]
    versions = []
    for combo in itertools.product(*paneGroups):
        entries, exits, switches = [], [], []
        for ptype, group in zip(paneTypes, combo):
            if ptype == "Entry":
                entries.extend(group)
            elif ptype == "Exit":
                exits.extend(group)
            elif ptype == "Switch":
                switches.extend(group)
        versions.append((entries, exits, switches))
    return versions


def _occurrences(version, getRule):
    """Prefixes are unique within a version only — each version is its own class,
    so there is no cross-version collision to avoid."""
    entries, exits, switches = version
    occ = []
    for i, item in enumerate(entries, 1):
        occ.append(_Occ(item, getRule(item.name), f"E{i}_", "entry"))
    for i, item in enumerate(exits, 1):
        occ.append(_Occ(item, getRule(item.name), f"X{i}_", "exit"))
    for i, item in enumerate(switches, 1):
        occ.append(_Occ(item, getRule(item.name), f"S{i}_", "switch"))
    return occ


# --- emitter ----------------------------------------------------------------

def _hookLines(occs, attr, level):
    out = []
    for o in occs:
        h = o.hook(attr)
        if h:
            out.append(_indent(h, level))
    return out


def _conditionSegment(occs, title, lineBuilder):
    if not occs:
        return []
    out = ["", f"        // -- {title} --"]
    out.extend(_hookLines(occs, "preConditionHook", 2))
    for o in occs:
        long_, short_ = o.conditions()
        out.extend(lineBuilder(long_, short_))
    out.extend(_hookLines(occs, "postConditionHook", 2))
    return out


def _entryLines(long_, short_):
    out = []
    if long_:
        out.append(f"        enterLong = enterLong && ({long_});")
    if short_:
        out.append(f"        enterShort = enterShort && ({short_});")
    return out


def _exitLines(long_, short_):
    out = []
    if long_:
        out.append(f"        exitLong = exitLong || ({long_});")
    if short_:
        out.append(f"        exitShort = exitShort || ({short_});")
    return out


def _switchLines(long_, short_):
    """A switch both blocks new entries and forces an exit on the same side."""
    out = []
    if long_:
        out.append(f"        enterLong = enterLong && !({long_});")
    if short_:
        out.append(f"        enterShort = enterShort && !({short_});")
    if long_:
        out.append(f"        exitLong = exitLong || ({long_});")
    if short_:
        out.append(f"        exitShort = exitShort || ({short_});")
    return out


def _summaryComment(occs):
    parts = []
    for role, label in (("entry", "entries"), ("exit", "exits"), ("switch", "switches")):
        names = [o.rule.name for o in occs if o.role == role]
        if names:
            parts.append(f"{label} {', '.join(names)}")
    return "; ".join(parts) if parts else "no rules"


def _classLines(cls, regName, occs):
    entries = [o for o in occs if o.role == "entry"]
    exits = [o for o in occs if o.role == "exit"]
    switches = [o for o in occs if o.role == "switch"]

    inputs, locals_ = [], []
    for o in occs:
        inputs.extend(o.inputDecls())
        locals_.extend(o.localDecls())

    lines = [f'// "{regName}": {_summaryComment(occs)}']
    if not entries:
        lines.append("// No entry rules, so this version enters every bar "
                     "(StrategyGeneratorTS parity).")
    lines.append(f"class {cls} : public Strategy {{")
    lines.append("public:")

    if inputs:
        lines.append(f"    {cls}()")
        inits = [
            f'{name}_h_(DeclareInput("{name}", {start}, {stop}, {step}))'
            for name, start, stop, step in inputs
        ]
        for i, init in enumerate(inits):
            lead = "        : " if i == 0 else "          "
            tail = " {}" if i == len(inits) - 1 else ","
            lines.append(lead + init + tail)
    else:
        lines.append(f"    {cls}() = default;")

    lines.append("")
    lines.append("    void OnBarClose(Context& ctx) override {")
    for alias in _ALIASES:
        lines.append(f"        const auto& {alias} = ctx.{alias};")
    if inputs:
        lines.append("")
        for name, _, _, _ in inputs:
            lines.append(f"        const double {name} = Input({name}_h_);")
    lines.append("")
    lines.append("        bool enterLong = true, enterShort = true;")
    lines.append("        bool exitLong = false, exitShort = false;")

    startHooks = _hookLines(occs, "startOfFileHook", 2)
    if startHooks:
        lines.append("")
        lines.append("        // -- Start of bar --")
        lines.extend(startHooks)

    lines.extend(_conditionSegment(entries, "Entries", _entryLines))
    lines.extend(_conditionSegment(exits, "Exits", _exitLines))
    lines.extend(_conditionSegment(switches, "Switches", _switchLines))

    # Reproduces the TS no-pyramiding guards; EnterLong while short auto-reverses,
    # which is what the TS `Buy` did too.
    lines.append("")
    lines.append("        // -- Order placement --")
    lines.append("        if (enterLong && ctx.MarketPosition() <= 0) ctx.EnterLong(1);")
    lines.append("        if (enterShort && ctx.MarketPosition() >= 0) ctx.EnterShort(1);")
    lines.append("        if (exitLong && ctx.MarketPosition() > 0) ctx.Exit();")
    lines.append("        if (exitShort && ctx.MarketPosition() < 0) ctx.Exit();")

    endHooks = _hookLines(occs, "endOfFileHook", 2)
    if endHooks:
        lines.append("")
        lines.append("        // -- End of bar --")
        lines.extend(endHooks)

    lines.append("    }")

    lines.append("")
    lines.append("private:")
    memberHooks = _hookLines(occs, "classMembersHook", 1)
    if memberHooks:
        lines.extend(memberHooks)
        lines.append("")
    for name, _, _, _ in inputs:
        lines.append(f"    std::size_t {name}_h_;")
    for name, typeText, init in locals_:
        lines.append(f"    {typeText} {name} = {init};")
    if not inputs and not locals_ and not memberHooks:
        lines.append("    // no state")
    lines.append("};")
    return lines


def _loadRuleCached():
    cache = {}

    def getRule(name):
        if name not in cache:
            cache[name] = ruleIO.loadRule(name)
        return cache[name]

    return getRule


def buildHeaderText(strategyName, panes, getRule=None):
    """Pure text: returns (headerText, [(registryName, className)]).
    getRule defaults to loading from the rules directory; tests pass their own."""
    if getRule is None:
        getRule = _loadRuleCached()

    versions = _enumerateVersions(panes)
    if not versions:
        raise GenerationError("There are no rule panes to generate from.")

    lines = [
        "#pragma once",
        "",
        f"// {strategyName}",
        f"// {_AUTOGEN}",
        "",
        '#include "bt/sim/strategy.h"',
        "",
        "#ifdef _MSC_VER",
        "#pragma warning(push)",
        f"#pragma warning(disable: {_MSVC_WARNINGS})",
        "#endif",
        "",
        "namespace bt {",
    ]

    entries = []
    for vIndex, version in enumerate(versions, 1):
        cls = className(strategyName, vIndex)
        regName = registryName(strategyName, vIndex)
        lines.append("")
        lines.extend(_classLines(cls, regName, _occurrences(version, getRule)))
        entries.append((regName, cls))

    lines.extend([
        "",
        "}  // namespace bt",
        "",
        "#ifdef _MSC_VER",
        "#pragma warning(pop)",
        "#endif",
    ])
    return "\n".join(lines) + "\n", entries


# --- manifest and .inc aggregation -----------------------------------------

def manifestPath(generatedDir):
    return os.path.join(generatedDir, MANIFEST_NAME)


def loadManifest(generatedDir):
    path = manifestPath(generatedDir)
    if not os.path.exists(path):
        return {}
    try:
        with open(path) as f:
            data = json.load(f)
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def _saveManifest(generatedDir, manifest):
    with open(manifestPath(generatedDir), "w") as f:
        json.dump(manifest, f, indent=4, sort_keys=True)


def _prune(manifest, generatedDir, keep=()):
    """Drop batches whose header no longer exists on disk — a hand-deleted header
    must not leave a dangling #include behind. `keep` names batches whose header
    is about to be written."""
    return {
        name: batch
        for name, batch in manifest.items()
        if name in keep or os.path.exists(os.path.join(generatedDir, batch["header"]))
    }


def _checkCollisions(manifest):
    seenEntries, seenHeaders = {}, {}
    for strategy in sorted(manifest):
        batch = manifest[strategy]
        header = batch["header"]
        if header in seenHeaders and seenHeaders[header] != strategy:
            raise GenerationError(
                f"Strategies '{seenHeaders[header]}' and '{strategy}' both generate "
                f"'{header}'. Rename one of them."
            )
        seenHeaders[header] = strategy
        for entry in batch["entries"]:
            name = entry["name"]
            if name in seenEntries and seenEntries[name] != strategy:
                raise GenerationError(
                    f"Registry name '{name}' is claimed by both "
                    f"'{seenEntries[name]}' and '{strategy}'. Rename one of them."
                )
            seenEntries[name] = strategy


def _writeIncFiles(generatedDir, manifest):
    headerLines = [
        f"// {_AUTOGEN}",
        "//",
        "// Included at file scope by registry.cpp: one #include per generated header.",
    ]
    registryLines = [
        f"// {_AUTOGEN}",
        "//",
        "// Included inside the braced initializer of the strategy table in",
        "// registry.cpp, so every line is a comma-terminated map entry.",
    ]
    for strategy in sorted(manifest):
        batch = manifest[strategy]
        headerLines.append(f'#include "{INCLUDE_DIR}/{batch["header"]}"')
        for entry in batch["entries"]:
            registryLines.append(
                f'{{"{entry["name"]}", [] {{ return std::make_unique<{entry["class"]}>(); }}}},'
            )

    headersPath = os.path.join(generatedDir, HEADERS_INC)
    registryPath = os.path.join(generatedDir, REGISTRY_INC)
    with open(headersPath, "w") as f:
        f.write("\n".join(headerLines) + "\n")
    with open(registryPath, "w") as f:
        f.write("\n".join(registryLines) + "\n")
    return headersPath, registryPath


def rebuildIncFiles(generatedDir):
    """Rewrite headers.inc and registry.inc from the manifest, dropping batches
    whose header has been deleted. Returns (headersPath, registryPath)."""
    manifest = _prune(loadManifest(generatedDir), generatedDir)
    _checkCollisions(manifest)
    _saveManifest(generatedDir, manifest)
    return _writeIncFiles(generatedDir, manifest)


# --- top-level generation ---------------------------------------------------

@dataclass
class GenerationResult:
    headerPath: str
    headersIncPath: str
    registryIncPath: str
    generatedDir: str
    entries: list = field(default_factory=list)  # [(registryName, className)]

    @property
    def versionCount(self):
        return len(self.entries)


def generatedDirFor(cfg):
    engineDir = (cfg.get("engineDir") or "").strip()
    if not engineDir:
        raise GenerationError("No BacktestEngine root is configured.")
    subdir = cfg.get("generatedSubdir") or INCLUDE_DIR
    return os.path.normpath(os.path.join(engineDir, subdir))


def generate(strategyName, panes, cfg):
    """Write the strategy header into the engine tree and refresh the registry
    includes. Raises GenerationError with a message fit for a dialog."""
    strategyName = (strategyName or "").strip()
    if not strategyName:
        raise GenerationError("Strategy name is required.")
    if ILLEGAL_NAME_CHARS.search(strategyName):
        raise GenerationError(
            'Strategy name cannot contain any of: \\ / : * ? " < > |'
        )

    generatedDir = generatedDirFor(cfg)
    headerName = headerFileName(strategyName)

    # Build (and validate) the text before touching disk, so a bad parameter
    # range leaves the engine tree exactly as it was.
    text, entries = buildHeaderText(strategyName, panes)

    manifest = _prune(loadManifest(generatedDir), generatedDir, keep=(strategyName,))
    manifest[strategyName] = {
        "header": headerName,
        "entries": [{"name": n, "class": c} for n, c in entries],
    }
    _checkCollisions(manifest)

    os.makedirs(generatedDir, exist_ok=True)
    headerPath = os.path.join(generatedDir, headerName)
    with open(headerPath, "w") as f:
        f.write(text)
    _saveManifest(generatedDir, manifest)
    headersIncPath, registryIncPath = _writeIncFiles(generatedDir, manifest)

    return GenerationResult(
        headerPath=headerPath,
        headersIncPath=headersIncPath,
        registryIncPath=registryIncPath,
        generatedDir=generatedDir,
        entries=entries,
    )
