import json
import os
import sys
import tempfile
import unittest
from unittest import mock

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import ruleIO
import strategyWriter as sw
from rule import Rule
from strategyWriter import GenerationError

DELIMITER = "------------------------------"


class Item:
    """Stands in for mainGUI.RuleItem (duck-typed by the writer)."""

    def __init__(self, name, flipped=False, negated=False, params=None):
        self.name = name
        self.flipped = flipped
        self.negated = negated
        self.params = params or {}


class Pane:
    """Stands in for mainGUI.RulePane."""

    def __init__(self, ruleType, items):
        self.ruleType = ruleType
        self.items = items


MOMENTUM = Rule(
    name="Momentum",
    type="Entry",
    inputVariables={"Length": "20"},
    longCondition="close[0] > close[Length]",
    shortCondition="close[0] < close[Length]",
)

STOP_LOSS = Rule(
    name="StopLoss",
    type="Exit",
    inputVariables={"stopLoss": "1000"},
    longCondition="ctx.OpenPositionProfit() < -stopLoss",
    shortCondition="ctx.OpenPositionProfit() < -stopLoss",
)

MONTHLY_TARGET = Rule(
    name="MonthlyTarget",
    type="Switch",
    inputVariables={"target": "5000"},
    localVariables={
        "monthProfit": {"type": "double", "init": "0.0"},
        "ii": {"type": "int", "init": "0"},
    },
    classMembersHook="double Half(double x) const { return x / 2.0; }",
    startOfFileHook="if (ctx.CurrentBar() == 1) { monthProfit = 0.0; }",
    preConditionHook="monthProfit += ctx.OpenPositionProfit();",
    longCondition="monthProfit > target",
    shortCondition="monthProfit > target",
    endOfFileHook="ii = ii + 1;",
)

RULES = {r.name: r for r in (MOMENTUM, STOP_LOSS, MONTHLY_TARGET)}


def getRule(name):
    return RULES[name]


def build(strategyName, panes):
    return sw.buildHeaderText(strategyName, panes, getRule=getRule)


def readText(path):
    with open(path) as f:
        return f.read()


def momentumPane(params=None):
    return Pane("Entry", [Item("Momentum", params=params)])


# The full expected header for one entry + one exit + one switch. Golden text:
# every change to the emitter must be a deliberate edit here.
GOLDEN = '''#pragma once

// Momentum Clone
// Auto-generated by StrategyGeneratorBE. Do not edit by hand.

#include "bt/sim/strategy.h"

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4101 4189 4244 4456)
#endif

namespace bt {

// "Momentum Clone V1": entries Momentum; exits StopLoss; switches MonthlyTarget
class Gen_Momentum_Clone_V1 : public Strategy {
public:
    Gen_Momentum_Clone_V1()
        : E1_Length_h_(DeclareInput("E1_Length", 5, 50, 5)),
          X1_stopLoss_h_(DeclareInput("X1_stopLoss", 1000, 1000, 0)),
          S1_target_h_(DeclareInput("S1_target", 5000, 5000, 0)) {}

    void OnBarClose(Context& ctx) override {
        const auto& open = ctx.open;
        const auto& high = ctx.high;
        const auto& low = ctx.low;
        const auto& close = ctx.close;
        const auto& volume = ctx.volume;

        const double E1_Length = Input(E1_Length_h_);
        const double X1_stopLoss = Input(X1_stopLoss_h_);
        const double S1_target = Input(S1_target_h_);

        bool enterLong = true, enterShort = true;
        bool exitLong = false, exitShort = false;

        // -- Start of bar --
        if (ctx.CurrentBar() == 1) { S1_monthProfit = 0.0; }

        // -- Entries --
        enterLong = enterLong && (close[0] > close[E1_Length]);
        enterShort = enterShort && (close[0] < close[E1_Length]);

        // -- Exits --
        exitLong = exitLong || (ctx.OpenPositionProfit() < -X1_stopLoss);
        exitShort = exitShort || (ctx.OpenPositionProfit() < -X1_stopLoss);

        // -- Switches --
        S1_monthProfit += ctx.OpenPositionProfit();
        enterLong = enterLong && !(S1_monthProfit > S1_target);
        enterShort = enterShort && !(S1_monthProfit > S1_target);
        exitLong = exitLong || (S1_monthProfit > S1_target);
        exitShort = exitShort || (S1_monthProfit > S1_target);

        // -- Order placement --
        if (enterLong && ctx.MarketPosition() <= 0) ctx.EnterLong(1);
        if (enterShort && ctx.MarketPosition() >= 0) ctx.EnterShort(1);
        if (exitLong && ctx.MarketPosition() > 0) ctx.Exit();
        if (exitShort && ctx.MarketPosition() < 0) ctx.Exit();

        // -- End of bar --
        S1_ii = S1_ii + 1;
    }

private:
    double Half(double x) const { return x / 2.0; }

    std::size_t E1_Length_h_;
    std::size_t X1_stopLoss_h_;
    std::size_t S1_target_h_;
    double S1_monthProfit = 0.0;
    int S1_ii = 0;
};

}  // namespace bt

#ifdef _MSC_VER
#pragma warning(pop)
#endif
'''


class TestGoldenHeader(unittest.TestCase):
    def testFullHeaderForOneOfEachRoleMatches(self):
        panes = [
            momentumPane({"Length": {"start": "5", "stop": "50", "step": "5"}}),
            Pane("Exit", [Item("StopLoss")]),
            Pane("Switch", [Item("MonthlyTarget")]),
        ]
        text, entries = build("Momentum Clone", panes)
        self.assertEqual(text, GOLDEN)
        self.assertEqual(entries, [("Momentum Clone V1", "Gen_Momentum_Clone_V1")])


class TestSanitizeIdentifier(unittest.TestCase):
    def testSpacesAndPunctuationBecomeUnderscores(self):
        self.assertEqual(sw.sanitizeIdentifier("Momentum Clone"), "Momentum_Clone")
        self.assertEqual(sw.sanitizeIdentifier("A - B (2)"), "A_B_2")

    def testEdgeUnderscoresAreStripped(self):
        self.assertEqual(sw.sanitizeIdentifier(" Momentum "), "Momentum")

    def testLeadingDigitIsPrefixed(self):
        self.assertEqual(sw.sanitizeIdentifier("2Fast"), "S_2Fast")

    def testEmptyResultIsPrefixed(self):
        self.assertEqual(sw.sanitizeIdentifier("---"), "S_")

    def testKeywordIsRejected(self):
        with self.assertRaises(GenerationError):
            sw.sanitizeIdentifier("class")

    def testDerivedNames(self):
        self.assertEqual(sw.headerFileName("Momentum Clone"), "gen_momentum_clone.h")
        self.assertEqual(sw.className("Momentum Clone", 2), "Gen_Momentum_Clone_V2")
        self.assertEqual(sw.registryName("Momentum Clone", 2), "Momentum Clone V2")
        self.assertEqual(sw.specStem("Momentum Clone", 2), "momentum_clone_v2")


class TestRenameVars(unittest.TestCase):
    def testWholeWordOnly(self):
        self.assertEqual(
            sw._renameVars("Length + LengthTwo + xLength", {"Length": "1"}, "E1_"),
            "E1_Length + LengthTwo + xLength",
        )

    def testCaseSensitive(self):
        # The TS original matched case-insensitively because EL is; C++ is not,
        # so "close" must not be captured by a rule variable named "Close".
        self.assertEqual(
            sw._renameVars("close[0] > Close", {"Close": "1"}, "E1_"),
            "close[0] > E1_Close",
        )

    def testLongestNameFirst(self):
        text = sw._renameVars("len + lenTwo", {"len": "1", "lenTwo": "2"}, "E1_")
        self.assertEqual(text, "E1_len + E1_lenTwo")

    def testInputsAndLocalsShareTheNamespace(self):
        rule = Rule(
            name="R",
            inputVariables={"n": "1"},
            localVariables={"acc": {"type": "double", "init": "0"}},
            longCondition="acc > n",
        )
        text, _ = sw.buildHeaderText(
            "S", [Pane("Entry", [Item("R")])], getRule=lambda name: rule
        )
        self.assertIn("enterLong = enterLong && (E1_acc > E1_n);", text)


class TestFlipAndNegate(unittest.TestCase):
    def _conditions(self, **itemKwargs):
        text, _ = build("S", [Pane("Entry", [Item("Momentum", **itemKwargs)])])
        return text

    def testPlain(self):
        text = self._conditions()
        self.assertIn("enterLong = enterLong && (close[0] > close[E1_Length]);", text)

    def testFlipSwapsLongAndShort(self):
        text = self._conditions(flipped=True)
        self.assertIn("enterLong = enterLong && (close[0] < close[E1_Length]);", text)
        self.assertIn("enterShort = enterShort && (close[0] > close[E1_Length]);", text)

    def testNegateWrapsInNot(self):
        text = self._conditions(negated=True)
        self.assertIn(
            "enterLong = enterLong && (!( close[0] > close[E1_Length] ));", text
        )

    def testFlipThenNegate(self):
        text = self._conditions(flipped=True, negated=True)
        self.assertIn(
            "enterLong = enterLong && (!( close[0] < close[E1_Length] ));", text
        )


class TestEmptyConditions(unittest.TestCase):
    def testMissingShortConditionEmitsNoShortLine(self):
        rule = Rule(name="LongOnly", longCondition="close[0] > close[1]")
        text, _ = sw.buildHeaderText(
            "S", [Pane("Entry", [Item("LongOnly")])], getRule=lambda n: rule
        )
        self.assertIn("enterLong = enterLong &&", text)
        self.assertNotIn("enterShort = enterShort &&", text)

    def testVersionWithNoEntriesIsCommented(self):
        text, _ = build("S", [Pane("Exit", [Item("StopLoss")])])
        self.assertIn("enters every bar", text)


class TestInputDeclarations(unittest.TestCase):
    def _decl(self, params):
        text, _ = build("S", [momentumPane(params)])
        for line in text.splitlines():
            if "DeclareInput" in line:
                return line.strip()
        return ""

    def testFullRangeIsUsed(self):
        self.assertIn(
            'DeclareInput("E1_Length", 5, 50, 5)',
            self._decl({"Length": {"start": "5", "stop": "50", "step": "5"}}),
        )

    def testNoParamsFallsBackToTheRuleDefault(self):
        self.assertIn('DeclareInput("E1_Length", 20, 20, 0)', self._decl(None))

    def testStartOnlyPinsTheInput(self):
        self.assertIn(
            'DeclareInput("E1_Length", 30, 30, 0)',
            self._decl({"Length": {"start": "30", "stop": "", "step": ""}}),
        )

    def testStopEqualToStartPinsTheInput(self):
        # grid.cpp returns 1 iteration for stop == start before it checks step.
        self.assertIn(
            'DeclareInput("E1_Length", 30, 30, 0)',
            self._decl({"Length": {"start": "30", "stop": "30", "step": "5"}}),
        )

    def testBlankStepPinsTheInput(self):
        self.assertIn(
            'DeclareInput("E1_Length", 5, 5, 0)',
            self._decl({"Length": {"start": "5", "stop": "50", "step": ""}}),
        )

    def testIndivisibleSpanIsRejected(self):
        with self.assertRaises(GenerationError) as cm:
            self._decl({"Length": {"start": "5", "stop": "50", "step": "7"}})
        self.assertIn("Length", str(cm.exception))
        self.assertIn("Momentum", str(cm.exception))

    def testStopBelowStartIsRejected(self):
        with self.assertRaises(GenerationError):
            self._decl({"Length": {"start": "50", "stop": "5", "step": "5"}})


class TestVersionEnumeration(unittest.TestCase):
    def testDelimiterSplitsAPaneIntoVersions(self):
        pane = Pane("Entry", [Item("Momentum"), DELIMITER, Item("Momentum")])
        text, entries = build("Multi", [pane])
        self.assertEqual(
            entries,
            [("Multi V1", "Gen_Multi_V1"), ("Multi V2", "Gen_Multi_V2")],
        )
        self.assertIn("class Gen_Multi_V1 : public Strategy {", text)
        self.assertIn("class Gen_Multi_V2 : public Strategy {", text)

    def testVersionsAreTheCrossProductOfPanes(self):
        panes = [
            Pane("Entry", [Item("Momentum"), DELIMITER, Item("Momentum")]),
            Pane("Exit", [Item("StopLoss"), DELIMITER, Item("StopLoss")]),
        ]
        _, entries = build("Multi", panes)
        self.assertEqual(len(entries), 4)

    def testEmptyGroupIsAValidVersion(self):
        pane = Pane("Entry", [Item("Momentum"), DELIMITER])
        _, entries = build("Multi", [pane])
        self.assertEqual(len(entries), 2)

    def testPrefixesRestartInEachVersion(self):
        pane = Pane("Entry", [Item("Momentum"), DELIMITER, Item("Momentum")])
        text, _ = build("Multi", [pane])
        # Per-version classes mean no V-part is needed to stay unique.
        self.assertEqual(text.count('DeclareInput("E1_Length"'), 2)

    def testNoPanesIsAnError(self):
        with self.assertRaises(GenerationError):
            build("Multi", [])

    def testOccurrencePrefixesCountUpWithinARole(self):
        pane = Pane("Entry", [Item("Momentum"), Item("Momentum")])
        text, _ = build("Multi", [pane])
        self.assertIn('DeclareInput("E1_Length"', text)
        self.assertIn('DeclareInput("E2_Length"', text)


class TestManifestAndIncFiles(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.dir = self._tmp.name
        self.addCleanup(self._tmp.cleanup)

    def _batch(self, header, entries):
        return {"header": header, "entries": [{"name": n, "class": c} for n, c in entries]}

    def _touch(self, name):
        with open(os.path.join(self.dir, name), "w") as f:
            f.write("// header\n")

    def testIncFilesListEveryBatch(self):
        manifest = {
            "Alpha": self._batch("gen_alpha.h", [("Alpha V1", "Gen_Alpha_V1")]),
            "Beta": self._batch("gen_beta.h", [("Beta V1", "Gen_Beta_V1")]),
        }
        self._touch("gen_alpha.h")
        self._touch("gen_beta.h")
        with open(sw.manifestPath(self.dir), "w") as f:
            json.dump(manifest, f)

        headersPath, registryPath = sw.rebuildIncFiles(self.dir)
        headers = readText(headersPath)
        registry = readText(registryPath)

        self.assertIn('#include "bt/strategies/generated/gen_alpha.h"', headers)
        self.assertIn('#include "bt/strategies/generated/gen_beta.h"', headers)
        self.assertIn(
            '{"Alpha V1", [] { return std::make_unique<Gen_Alpha_V1>(); }},', registry
        )
        # Every entry line must be comma-terminated: it lands inside a braced
        # initializer in registry.cpp.
        for line in registry.splitlines():
            if not line.startswith("//"):
                self.assertTrue(line.endswith(","), line)

    def testBatchWithAMissingHeaderIsPruned(self):
        manifest = {
            "Alpha": self._batch("gen_alpha.h", [("Alpha V1", "Gen_Alpha_V1")]),
            "Gone": self._batch("gen_gone.h", [("Gone V1", "Gen_Gone_V1")]),
        }
        self._touch("gen_alpha.h")
        with open(sw.manifestPath(self.dir), "w") as f:
            json.dump(manifest, f)

        headersPath, registryPath = sw.rebuildIncFiles(self.dir)
        self.assertNotIn("gen_gone.h", readText(headersPath))
        self.assertNotIn("Gone V1", readText(registryPath))
        self.assertNotIn("Gone", sw.loadManifest(self.dir))

    def testEmptyManifestWritesCommentOnlyFiles(self):
        headersPath, registryPath = sw.rebuildIncFiles(self.dir)
        for path in (headersPath, registryPath):
            for line in readText(path).splitlines():
                self.assertTrue(line.startswith("//"), line)

    def testDuplicateRegistryNameAcrossBatchesIsRejected(self):
        manifest = {
            "Alpha": self._batch("gen_alpha.h", [("Shared V1", "Gen_Alpha_V1")]),
            "Beta": self._batch("gen_beta.h", [("Shared V1", "Gen_Beta_V1")]),
        }
        self._touch("gen_alpha.h")
        self._touch("gen_beta.h")
        with open(sw.manifestPath(self.dir), "w") as f:
            json.dump(manifest, f)
        with self.assertRaises(GenerationError) as cm:
            sw.rebuildIncFiles(self.dir)
        self.assertIn("Shared V1", str(cm.exception))

    def testTwoStrategiesSharingAHeaderNameIsRejected(self):
        manifest = {
            "Momentum Clone": self._batch("gen_momentum_clone.h", [("A V1", "Gen_A_V1")]),
            "Momentum-Clone": self._batch("gen_momentum_clone.h", [("B V1", "Gen_B_V1")]),
        }
        self._touch("gen_momentum_clone.h")
        with open(sw.manifestPath(self.dir), "w") as f:
            json.dump(manifest, f)
        with self.assertRaises(GenerationError) as cm:
            sw.rebuildIncFiles(self.dir)
        self.assertIn("gen_momentum_clone.h", str(cm.exception))

    def testMissingManifestIsAnEmptyOne(self):
        self.assertEqual(sw.loadManifest(self.dir), {})

    def testCorruptManifestIsAnEmptyOne(self):
        with open(sw.manifestPath(self.dir), "w") as f:
            f.write("{ not json")
        self.assertEqual(sw.loadManifest(self.dir), {})


class TestGenerate(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.engineDir = self._tmp.name
        self.addCleanup(self._tmp.cleanup)
        self.cfg = {
            "engineDir": self.engineDir,
            "generatedSubdir": "src/bt/strategies/generated",
        }
        patcher = mock.patch.object(ruleIO, "loadRule", side_effect=getRule)
        patcher.start()
        self.addCleanup(patcher.stop)

    def generatedDir(self):
        return os.path.join(
            self.engineDir, "src", "bt", "strategies", "generated"
        )

    def testWritesHeaderManifestAndIncFiles(self):
        result = sw.generate("Momentum Clone", [momentumPane()], self.cfg)

        self.assertTrue(os.path.exists(result.headerPath))
        self.assertEqual(os.path.basename(result.headerPath), "gen_momentum_clone.h")
        self.assertEqual(result.versionCount, 1)
        self.assertEqual(
            result.entries, [("Momentum Clone V1", "Gen_Momentum_Clone_V1")]
        )

        manifest = sw.loadManifest(self.generatedDir())
        self.assertEqual(manifest["Momentum Clone"]["header"], "gen_momentum_clone.h")
        self.assertIn(
            "Momentum Clone V1", readText(result.registryIncPath)
        )
        self.assertIn("gen_momentum_clone.h", readText(result.headersIncPath))

    def testRegeneratingReplacesTheStrategysOwnBatch(self):
        pane = Pane("Entry", [Item("Momentum"), DELIMITER, Item("Momentum")])
        sw.generate("Momentum Clone", [pane], self.cfg)
        result = sw.generate("Momentum Clone", [momentumPane()], self.cfg)

        registry = readText(result.registryIncPath)
        self.assertIn("Momentum Clone V1", registry)
        self.assertNotIn("Momentum Clone V2", registry)

    def testASecondStrategyCoexists(self):
        sw.generate("Alpha", [momentumPane()], self.cfg)
        result = sw.generate("Beta", [momentumPane()], self.cfg)

        registry = readText(result.registryIncPath)
        self.assertIn("Alpha V1", registry)
        self.assertIn("Beta V1", registry)
        headers = readText(result.headersIncPath)
        self.assertIn("gen_alpha.h", headers)
        self.assertIn("gen_beta.h", headers)

    def testBadParameterRangeLeavesTheEngineTreeUntouched(self):
        pane = momentumPane({"Length": {"start": "5", "stop": "50", "step": "7"}})
        with self.assertRaises(GenerationError):
            sw.generate("Momentum Clone", [pane], self.cfg)
        self.assertFalse(os.path.exists(self.generatedDir()))

    def testBlankNameIsRejected(self):
        with self.assertRaises(GenerationError):
            sw.generate("  ", [momentumPane()], self.cfg)

    def testIllegalFilenameCharIsRejected(self):
        with self.assertRaises(GenerationError):
            sw.generate("Momentum/Clone", [momentumPane()], self.cfg)

    def testMissingEngineDirIsRejected(self):
        with self.assertRaises(GenerationError):
            sw.generate("Momentum Clone", [momentumPane()], {"engineDir": ""})


if __name__ == "__main__":
    unittest.main()
